/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testIfLowerBoundLessThanZero() {
        Integer[] arr = new Integer[]{1, 2, 3, 4};
        assertThrows(IllegalArgumentException.class,()->{App.medium(arr, 3, -1, 3);});
    }
    @Test
    public void testIfHigherBoundGreatherequalThanSize() {
        Integer[] arr = new Integer[]{1, 2, 3, 4};
        assertThrows(IllegalArgumentException.class,()->{App.medium(arr, 3, 1, 5);});
    }

    @Test
    public void testEmptyArray() {
        Integer[] arr = new Integer[0];
        assertThrows(IllegalArgumentException.class,()->{App.medium(arr, 3, 1, 2);});
    }

    @Test
    public void isEvaulateTrue() {
        Integer[] arr = new Integer[]{1, 2, 3, 4};
        assertEquals(5,App.medium(arr, 1, 1, 2));
    }

}
