/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw1;

public class App {
    public static double medium (Integer[] array, Integer howManyPeople, Integer lowerBound, Integer higerBound){
        if (array.length==0||lowerBound<0||higerBound>=array.length||lowerBound>higerBound){
            throw new IllegalArgumentException();
        }
        int sum=0;
        for(int i =lowerBound;i<=higerBound ; i++){
            sum+=array[i];
        }
        return sum/howManyPeople;
    }
}
